#!/bin/bash

new="$1"

show_usage() {
    cat <<EOF
Usage: setbranding [options] [<new_branding_name>]

Program shows or change current branding

Valid options are:
  --help    display help screen

  <new_branding_name> is full two-word or short name of branding

Examples:

  # setbranding

  Run program without branding name displays current branding packages

  # setbranding altlinux-centaurus

  Change branding to altlinux-centaurus (altlinux- may be omitted)

Report bugs to http://bugs.altlinux.org
EOF
    exit
}

show_priv() {
    echo "Change branding requires root privileges. Program is terminated."
    exit 1
}

if [ -z "$new" ]
then

    # Show installed branding pacakges
	rpm -qa branding-\* --qf '%{name}\n'

else

    # Show usage information
    test "$new" = "--help" && show_usage

    # Check privileges
    test -w "/boot/grub/grub.cfg" || show_priv

	# Strict branding name
	echo "$new" | grep '-' >/dev/null || new="altlinux-$new"
	echo -n "Change branding to $new? [Y/n] "
	read choice
	test "+$choice" = "+n" && exit
	packages="$(rpm -qa branding-\* --qf '%{name} ')"
	removed="$(echo $packages| sed 's/ /- /g')-"
	#apt-get update
	
	# Build list of packages with exclude missed packages
	installed="$(echo $packages| tr ' ' '\n' | cut -f4 -d- | sed "s/^/branding-$new-/"|sort)"
	installed="`comm -12 <(echo "$installed"|tr ' ' '\n') <(apt-cache pkgnames branding-$new|sort)`"
	#echo $installed $removed | tr ' ' '\n'

    # Replace old branding with new one
	apt-get install $installed $removed

    # Update Grub theme
    grub-mkconfig -o /boot/grub/grub.cfg

    # Generate newt bootsplash
    make-initrd
fi
